<?php
	$data = $block->getData();
	$singleData = $this->getSingleData($data['data']['postId']);
?>
<h1> Selected Post -  <?php echo $singleData->getTitle(); ?></h1><hr>
<div>
	<h3>Title</h3>
	<p><?php echo $singleData->getTitle(); ?></p>	
</div>
<div>
	<h3>Author</h3>
	<p><?php echo $singleData->getAuthor(); ?></p>
</div>
<div>
	<h3>Content</h3>
	<p><?php echo $singleData->getContent(); ?></p>
</div>
<div>
	<h3>Date</h3>
	<p><?php echo $singleData->getCreatedAt(); ?></p>
</div>